#!/usr/bin/env node
/* Builds every brand file from geometry: the tray-U (logo A, chosen 22 Sep 2026) followed
   directly by "Bite" in Archivo Bold, converted to outlines so the lockup never depends on a
   font loading. Nothing here is generated by a model.

   node scripts/brand.mjs            → assets/brand/*.svg|png and the path data for Logo.jsx
   node scripts/brand.mjs --preview  → assets/_raw/brand-preview.png only

   The U is drawn, not typed: its outer height is Archivo's cap height, its stroke is Archivo
   Bold's stem, and the three counters sit above it exactly as in the mark. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import opentype from 'opentype.js';
import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'assets', 'brand');
const FONT = path.join(ROOT, 'assets', '_raw', 'fonts', 'archivo-700.ttf');
const FONT_URL = 'https://cdn.jsdelivr.net/fontsource/fonts/archivo@latest/latin-700-normal.ttf';

// Colours are the tokens' literal values: these files leave the CSS world (app icons, OG image).
const C = { accent: '#1F4FD8', accentDark: '#7BA5FF', ink: '#11161B', paper: '#FFFFFF', inkDark: '#EDF1F4' };

async function loadFont() {
  if (!fs.existsSync(FONT)) {
    fs.mkdirSync(path.dirname(FONT), { recursive: true });
    const res = await fetch(FONT_URL);
    if (!res.ok) throw new Error(`font download HTTP ${res.status}`);
    fs.writeFileSync(FONT, Buffer.from(await res.arrayBuffer()));
  }
  const b = fs.readFileSync(FONT);
  return opentype.parse(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength));
}

const r1 = (n) => Math.round(n * 10) / 10;

/* Glyph by glyph with the font's kerning: opentype.js's shaper trips on Archivo's ccmp table,
   and a four-letter Latin word needs no shaping. */
function textPath(font, text, x, y) {
  const out = new opentype.Path();
  const glyphs = [...text].map((ch) => font.charToGlyph(ch));
  glyphs.forEach((gl, i) => {
    out.extend(gl.getPath(x, y, 1000));
    x += gl.advanceWidth + (glyphs[i + 1] ? font.getKerningValue(gl, glyphs[i + 1]) : 0);
  });
  return out;
}

/* All geometry in font units (1000/em), y down, baseline at BASE. */
const BASE = 1000;
function geometry(font, { width = 1.45, filled = 2, gap = 150 } = {}) {
  const cap = font.tables.os2.sCapHeight; // 686
  const stem = 145; // Archivo Bold vertical stem (I = 149, l = 139)
  const yc = BASE - cap;
  const Wu = Math.round(cap * width); // the tray is wider than a letter U: that is the mark
  const sw = stem;
  const x0 = 0;
  const xl = x0 + sw / 2, xr = x0 + Wu - sw / 2;
  const yt = yc - 8 + sw / 2; // round caps overshoot the cap line a hair, like round letters do
  const yb = BASE + 10 - sw / 2;
  const rc = Math.round(cap * 8 / 27); // the mark's corner radius, scaled
  const u = `M${r1(xl)} ${r1(yt)}V${r1(yb - rc)}A${rc} ${rc} 0 0 0 ${r1(xl + rc)} ${r1(yb)}H${r1(xr - rc)}A${rc} ${rc} 0 0 0 ${r1(xr)} ${r1(yb - rc)}V${r1(yt)}`;
  const span = xr - xl;
  const hr = Math.round(span * 0.1); // counters: the mark's 4/40 of the tray
  const hy = Math.round(yc - cap * 7.5 / 27);
  const heads = [0.225, 0.5, 0.775].map((f, i) => ({ cx: r1(xl + span * f), cy: hy, r: hr, on: i < filled }));
  const bx = x0 + Wu + gap - font.charToGlyph('B').leftSideBearing;
  const wordPath = textPath(font, 'Bite', bx, BASE);
  const word = wordPath.toPathData(1);
  const wordBox = wordPath.getBoundingBox();
  const box = { x: 0, y: hy - hr, w: Math.ceil(wordBox.x2), h: Math.ceil(BASE + 12 - (hy - hr)) };
  return { u, sw, heads, word, box, Wu, cap, yc };
}

function lockupSvg(g, { u = C.accent, word = C.ink, bg = null, pad = 24, ring = true, title = 'UBite' } = {}) {
  const vb = [g.box.x - pad, g.box.y - pad, g.box.w + pad * 2, g.box.h + pad * 2].map(Math.round);
  const heads = g.heads.map((h) => h.on || !ring
    ? `<circle cx="${h.cx}" cy="${h.cy}" r="${h.r}" fill="${u}"/>`
    : `<circle cx="${h.cx}" cy="${h.cy}" r="${h.r - 30}" fill="none" stroke="${u}" stroke-width="60"/>`).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb.join(' ')}" role="img" aria-label="${title}">` +
    (bg ? `<rect x="${vb[0]}" y="${vb[1]}" width="${vb[2]}" height="${vb[3]}" fill="${bg}"/>` : '') +
    `<path d="${g.u}" fill="none" stroke="${u}" stroke-width="${g.sw}" stroke-linecap="round" stroke-linejoin="round"/>${heads}` +
    `<path d="${g.word}" fill="${word}"/></svg>`;
}

/* The square app icon: the whole lockup, white on the accent, inside the maskable safe circle. */
function iconSvg(g, { size = 512, fill = 0.78, maskable = false, bg = C.accent, fg = C.paper, radius = 0 } = {}) {
  // A 3:1 lockup inscribed in the 80% safe circle (maskable) or filling `fill` of the width.
  const aspect = g.box.w / g.box.h;
  const safe = maskable ? 0.8 * size : size;
  const w = maskable ? Math.min(safe * 2 / Math.sqrt(4 + 4 / (aspect * aspect)) * 0.97, safe) : size * fill;
  const s = w / g.box.w;
  const h = g.box.h * s;
  const tx = (size - w) / 2 - g.box.x * s;
  const ty = (size - h) / 2 - g.box.y * s + h * 0.02;
  const heads = g.heads.map((hd) => `<circle cx="${hd.cx}" cy="${hd.cy}" r="${hd.r}" fill="${fg}"/>`).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">` +
    `<rect width="${size}" height="${size}" rx="${radius}" fill="${bg}"/>` +
    `<g transform="translate(${r1(tx)} ${r1(ty)}) scale(${s.toFixed(5)})">` +
    `<path d="${g.u}" fill="none" stroke="${fg}" stroke-width="${g.sw}" stroke-linecap="round" stroke-linejoin="round"/>${heads}` +
    `<path d="${g.word}" fill="${fg}"/></g></svg>`;
}

/* The browser tab stays the U alone: five letters at 16px are a grey smudge. */
function faviconSvg() {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">` +
    `<style>path{stroke:${C.accent}}circle{fill:${C.accent}}@media (prefers-color-scheme:dark){path{stroke:${C.accentDark}}circle{fill:${C.accentDark}}}</style>` +
    `<path d="M12 22v14a8 8 0 0 0 8 8h24a8 8 0 0 0 8-8V22" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>` +
    `<circle cx="21" cy="12" r="5"/><circle cx="32" cy="12" r="5"/><circle cx="43" cy="12" r="5"/></svg>`;
}

const png = (svg, file, size) => sharp(Buffer.from(svg), { density: 300 }).resize(size, size).png({ compressionLevel: 9 }).toFile(file);

const font = await loadFont();

if (process.argv.includes('--preview')) {
  // Width variants of the tray, on light and dark, plus the icon at launcher sizes.
  const rows = [];
  for (const width of [1.66, 1.45, 1.3]) {
    const g = geometry(font, { width });
    rows.push(lockupSvg(g, { pad: 120, bg: '#ECEFF3' }), lockupSvg(g, { u: C.accentDark, word: C.inkDark, pad: 120, bg: '#0D1116' }));
  }
  const tiles = await Promise.all(rows.map((s) => sharp(Buffer.from(s)).resize({ width: 560 }).png().toBuffer()));
  const metas = await Promise.all(tiles.map((t) => sharp(t).metadata()));
  const g = geometry(font, { width: 1.45 });
  const icons = await Promise.all([192, 96, 48].map((sz) => sharp(Buffer.from(iconSvg(g, { size: 512, radius: 112 }))).resize(sz, sz).png().toBuffer()));
  const H = metas.reduce((s, m, i) => (i % 2 ? s : s + m.height + 16), 16) + 220;
  const comp = [];
  let y = 16;
  for (let i = 0; i < tiles.length; i += 2) {
    comp.push({ input: tiles[i], left: 16, top: y }, { input: tiles[i + 1], left: 592, top: y });
    y += metas[i].height + 16;
  }
  let x = 16;
  for (const [i, sz] of [192, 96, 48].entries()) { comp.push({ input: icons[i], left: x, top: y }); x += sz + 24; }
  const out = path.join(ROOT, 'assets', '_raw', 'brand-preview.png');
  await sharp({ create: { width: 1168, height: H, channels: 3, background: '#FFFFFF' } }).composite(comp).png().toFile(out);
  console.log(`✓ ${path.relative(ROOT, out)}`);
} else {
  const g = geometry(font, { width: Number(process.env.TRAY_WIDTH || 1.45) });
  fs.mkdirSync(OUT, { recursive: true });
  const write = (name, s) => { fs.writeFileSync(path.join(OUT, name), s); console.log(`✓ assets/brand/${name}`); };
  write('logo.svg', lockupSvg(g));
  write('logo-on-dark.svg', lockupSvg(g, { u: C.accentDark, word: C.inkDark }));
  write('logo-white.svg', lockupSvg(g, { u: C.paper, word: C.paper, ring: false }));
  write('logo-mono.svg', lockupSvg(g, { u: 'currentColor', word: 'currentColor', ring: false }).replace('<svg ', '<svg fill="currentColor" '));
  write('favicon.svg', faviconSvg());
  write('app-icon.svg', iconSvg(g, { size: 512, fill: 0.8 }));
  const jobs = [
    ['icon-512.png', iconSvg(g, { size: 512, fill: 0.8 }), 512],
    ['icon-192.png', iconSvg(g, { size: 512, fill: 0.8 }), 192],
    ['icon-maskable-512.png', iconSvg(g, { size: 512, maskable: true }), 512],
    ['apple-touch-icon.png', iconSvg(g, { size: 512, fill: 0.8 }), 180],
    ['favicon-32.png', faviconSvg().replace(/<style>.*<\/style>/, `<style>path{stroke:${C.accent}}circle{fill:${C.accent}}</style>`), 32],
  ];
  for (const [name, svg, size] of jobs) { await png(svg, path.join(OUT, name), size); console.log(`✓ assets/brand/${name}`); }
  // Path data for components/brand/Logo.jsx, which draws the same lockup live.
  const data = { box: g.box, u: g.u, sw: g.sw, heads: g.heads.map(({ cx, cy, r }) => ({ cx, cy, r })), word: g.word };
  fs.writeFileSync(path.join(ROOT, 'assets', '_raw', 'lockup.json'), JSON.stringify(data));
  console.log('✓ assets/_raw/lockup.json (paste into Logo.jsx LOCKUP)');
}
