#!/usr/bin/env node
/* Imports what the team generated in Gemini (assets/gemini-prompts.md) into the locked UBite
   style. Drop the files in assets/_raw/gemini/ with the names the prompts ask for, then:

   node scripts/import-gemini.mjs            everything found
   node scripts/import-gemini.mjs spot-nap   one file (name without extension)

   spot-*.png|jpg   → match-ink (crop, stroke width of the approved characters) → vectorise →
                      assets/illustrations/spots/<name>.svg
   picto-*.png|jpg  → split into pictograms (names from PICTO_NAMES) → assets/illustrations/picto/
   doodles-*.png|jpg→ added to the doodle wallpaper, assets/patterns/canteen.svg
   flat-*.png|jpg   → cut to the palette → assets/illustrations/scenes/<name>.svg
   vid-*.mp4        → best seamless loop found automatically, sound removed, square crop, the
                      drawing keyed to white lines on black (so it takes the theme's colour with
                      mix-blend-mode) → assets/motion/spot-<name>.mp4 + .webm

   Every output gets a manifest row with the exact Gemini prompt, parsed from gemini-prompts.md. */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import ffmpeg from 'ffmpeg-static';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const IN = path.join(ROOT, 'assets', '_raw', 'gemini');
const node = (...a) => execFileSync(process.execPath, a, { cwd: ROOT, stdio: ['ignore', 'pipe', 'inherit'] }).toString().trim();
const rel = (p) => path.relative(ROOT, p).split(path.sep).join('/');

// Which pictogram is which, in reading order, per sheet. "-" = rejected, not imported.
const PICTO_NAMES = { 'picto-more': ['salad', '-', 'fish', 'sarmale', '-', 'covrig'] };
const LICENCE = 'Google Gemini output (Nano Banana / Veo), generated by the team — Google Generative AI terms; SynthID watermark embedded';

/* "**Salvează ca:** `spot-nap.png`" followed by a ``` block → { 'spot-nap': 'prompt…' } */
function prompts() {
  const md = fs.readFileSync(path.join(ROOT, 'assets', 'gemini-prompts.md'), 'utf8');
  const out = {};
  for (const m of md.matchAll(/Salvează ca:\*\* `([^`]+)`[\s\S]*?```\n([\s\S]*?)```/g)) out[m[1].replace(/\.\w+$/, '')] = m[2].replace(/\s+/g, ' ').trim();
  return out;
}

function record(file, name, derivedFrom, extra = '') {
  node('scripts/asset.mjs', 'record', file, '--source', `Gemini (${name.startsWith('vid-') ? 'Veo' : 'Nano Banana'}), ${derivedFrom}${extra}`,
    '--licence', LICENCE, '--prompt', PROMPTS[name] || '', '--status', 'final');
}

/* Seamless loop: the pair of frames (at least 1.5 s apart) that look most alike. */
function bestLoop(file, crop) {
  const raw = execFileSync(ffmpeg, ['-loglevel', 'error', '-i', file, '-vf', `${crop},scale=64:64,format=gray`, '-f', 'rawvideo', '-']);
  const n = raw.length / 4096;
  const f = (i) => raw.subarray(i * 4096, (i + 1) * 4096);
  const d = (a, b) => { let s = 0; for (let k = 0; k < 4096; k++) { const x = a[k] - b[k]; s += x * x; } return s / 4096; };
  let best = [Infinity, 0, n - 1];
  for (let i = 0; i < n; i++) for (let j = i + 36; j < n; j++) { const v = d(f(i), f(j)); if (v < best[0]) best = [v, i, j]; }
  return { start: best[1], end: best[2], mse: best[0] };
}

function videoSize(file) {
  // ffmpeg with no output exits 1 and prints the stream info on stderr.
  let info = '';
  try { execFileSync(ffmpeg, ['-hide_banner', '-i', file], { stdio: ['ignore', 'ignore', 'pipe'] }); } catch (e) { info = String(e.stderr); }
  const m = info.match(/, (\d{3,5})x(\d{3,5})/);
  return m ? [Number(m[1]), Number(m[2])] : [1280, 720];
}

const PROMPTS = prompts();
const only = process.argv[2];
const files = fs.readdirSync(IN).filter((f) => /\.(png|jpe?g|mp4)$/i.test(f) && !/-loop\.|^_/.test(f))
  .filter((f) => !only || f.replace(/\.\w+$/, '') === only).sort();

const doodleSheets = [];
for (const f of files) {
  const file = path.join(IN, f);
  const name = f.replace(/\.\w+$/, '');
  if (name.startsWith('spot-')) {
    const inked = path.join(IN, `_${name}-inked.png`);
    const svg = path.join(IN, `_${name}-vector.svg`);
    const out = path.join(ROOT, 'assets', 'illustrations', 'spots', `${name.slice(5)}.svg`);
    console.log(node('scripts/match-ink.mjs', file, inked, '--target', '16'));
    node('scripts/asset.mjs', 'vectorize', inked, svg, '--threshold', '140', '--turd', '30');
    fs.copyFileSync(svg, out);
    record(out, name, `assets/_raw/gemini/${f}, stroke matched to the approved characters and vectorised`);
    console.log(`✓ ${rel(out)}`);
  } else if (name.startsWith('picto-')) {
    const names = PICTO_NAMES[name] || [];
    const keep = names.filter((x) => x !== '-');
    node('scripts/asset.mjs', 'picto', file, 'assets/illustrations/picto', '--names', names.map((x, i) => (x === '-' ? `rejected${i}` : x)).join(','), '--only', keep.join(','));
    for (const k of keep) record(`assets/illustrations/picto/picto-${k}.svg`, name, `assets/_raw/gemini/${f}, split and traced in two layers`);
    console.log(`✓ pictograms: ${keep.join(', ')}`);
  } else if (name.startsWith('doodles-')) {
    doodleSheets.push(file);
  } else if (name.startsWith('flat-')) {
    const out = path.join(ROOT, 'assets', 'illustrations', 'scenes', `${name.slice(5)}.svg`);
    node('scripts/asset.mjs', 'flatten', file, out);
    record(out, name, `assets/_raw/gemini/${f}, cut to the palette, one layer per token colour`);
    console.log(`✓ ${rel(out)}`);
  } else if (name.startsWith('vid-')) {
    // The drawing sits in the middle of a 16:9 frame; a centred square keeps all of it.
    const [w, h] = videoSize(file);
    const crop = `crop=${h}:${h}:${Math.round((w - h) / 2)}:0`;
    const { start, end, mse } = bestLoop(file, crop);
    const vf = `select='between(n\\,${start}\\,${end - 1})',setpts=N/24/TB,${crop},format=gbrp,extractplanes=r,lut=y='clip((val-70)*255/150\\,0\\,255)',scale=540:540,format=yuv420p`;
    const base = path.join(ROOT, 'assets', 'motion', `spot-${name.slice(4)}`);
    execFileSync(ffmpeg, ['-loglevel', 'error', '-y', '-i', file, '-vf', vf, '-an', '-r', '24', '-c:v', 'libx264', '-preset', 'slow', '-crf', '24', '-movflags', '+faststart', `${base}.mp4`]);
    execFileSync(ffmpeg, ['-loglevel', 'error', '-y', '-i', file, '-vf', vf, '-an', '-r', '24', '-c:v', 'libvpx-vp9', '-b:v', '0', '-crf', '38', '-row-mt', '1', `${base}.webm`]);
    for (const ext of ['mp4', 'webm']) record(`${base}.${ext}`, name, `assets/_raw/gemini/${f}, frames ${start}–${end - 1} as a seamless loop (mse ${mse.toFixed(1)}), keyed to white on black`);
    console.log(`✓ ${rel(base)}.mp4/.webm  loop ${start}–${end - 1} (${((end - start) / 24).toFixed(2)} s)`);
  }
}

if (doodleSheets.length) {
  const sheets = ['assets/_raw/doodles-canteen/doodles-canteen-s101.jpg', 'assets/_raw/doodles-student/doodles-student-s101.jpg', ...doodleSheets.map(rel)];
  console.log(node('scripts/asset.mjs', 'pattern', 'assets/patterns/canteen.svg', ...sheets, '--gap', '96'));
}
