/* Generated by scripts/logo-sketches.mjs — AI logo sketches shown in logo-picker.html. */
window.UBITE_AI_CONCEPTS = [
  {
    "id": "AI1",
    "name": "U-ul mușcat",
    "concept": "Schiță AI pentru N5: un U cu o mușcătură.",
    "src": "../../../../assets/explorations/logo/mark-bitten-u-s59749.webp"
  },
  {
    "id": "AI2",
    "name": "U-ul mușcat",
    "concept": "Schiță AI pentru N5: un U cu o mușcătură.",
    "src": "../../../../assets/explorations/logo/mark-bitten-u-s59750.webp"
  },
  {
    "id": "AI3",
    "name": "U-ul mușcat",
    "concept": "Schiță AI pentru N5: un U cu o mușcătură.",
    "src": "../../../../assets/explorations/logo/mark-bitten-u-s59751.webp"
  },
  {
    "id": "AI4",
    "name": "Bolul cu nivel",
    "concept": "Schiță AI pentru N1: un bol care se umple ca un indicator.",
    "src": "../../../../assets/explorations/logo/mark-bowl-level-s54008.webp"
  },
  {
    "id": "AI5",
    "name": "Tava cu compartimente",
    "concept": "Schiță AI pentru N2: tava de cantină văzută de sus.",
    "src": "../../../../assets/explorations/logo/mark-compartment-tray-s31886.webp"
  },
  {
    "id": "AI6",
    "name": "Tava cu compartimente",
    "concept": "Schiță AI pentru N2: tava de cantină văzută de sus.",
    "src": "../../../../assets/explorations/logo/mark-compartment-tray-s31887.webp"
  },
  {
    "id": "AI7",
    "name": "Tava cu compartimente",
    "concept": "Schiță AI pentru N2: tava de cantină văzută de sus.",
    "src": "../../../../assets/explorations/logo/mark-compartment-tray-s31888.webp"
  },
  {
    "id": "AI8",
    "name": "Paleta de afișaj",
    "concept": "Schiță AI pentru N8: paleta unui panou de plecări cu litera U.",
    "src": "../../../../assets/explorations/logo/mark-flap-tile-s53809.webp"
  },
  {
    "id": "AI9",
    "name": "Paleta de afișaj",
    "concept": "Schiță AI pentru N8: paleta unui panou de plecări cu litera U.",
    "src": "../../../../assets/explorations/logo/mark-flap-tile-s53810.webp"
  },
  {
    "id": "AI10",
    "name": "Paleta de afișaj",
    "concept": "Schiță AI pentru N8: paleta unui panou de plecări cu litera U.",
    "src": "../../../../assets/explorations/logo/mark-flap-tile-s53811.webp"
  },
  {
    "id": "AI11",
    "name": "Farfuria-ceas",
    "concept": "Schiță AI pentru N3: farfurie și cadran, felia arată așteptarea.",
    "src": "../../../../assets/explorations/logo/mark-plate-clock-s23362.webp"
  },
  {
    "id": "AI12",
    "name": "Farfuria-ceas",
    "concept": "Schiță AI pentru N3: farfurie și cadran, felia arată așteptarea.",
    "src": "../../../../assets/explorations/logo/mark-plate-clock-s23363.webp"
  },
  {
    "id": "AI13",
    "name": "Farfuria-ceas",
    "concept": "Schiță AI pentru N3: farfurie și cadran, felia arată așteptarea.",
    "src": "../../../../assets/explorations/logo/mark-plate-clock-s23364.webp"
  },
  {
    "id": "AI14",
    "name": "Lingura-U",
    "concept": "Schiță AI pentru N10: lingura care se îndoaie în litera U.",
    "src": "../../../../assets/explorations/logo/mark-spoon-u-s80260.webp"
  },
  {
    "id": "AI15",
    "name": "Lingura-U",
    "concept": "Schiță AI pentru N10: lingura care se îndoaie în litera U.",
    "src": "../../../../assets/explorations/logo/mark-spoon-u-s80261.webp"
  },
  {
    "id": "AI16",
    "name": "Lingura-U",
    "concept": "Schiță AI pentru N10: lingura care se îndoaie în litera U.",
    "src": "../../../../assets/explorations/logo/mark-spoon-u-s80262.webp"
  },
  {
    "id": "AI17",
    "name": "Tava-U și coada",
    "concept": "Schiță AI pentru A: tava văzută din lateral, cu trei capete la coadă.",
    "src": "../../../../assets/explorations/logo/mark-tray-queue-s34791.webp"
  },
  {
    "id": "AI18",
    "name": "Tava-U și coada",
    "concept": "Schiță AI pentru A: tava văzută din lateral, cu trei capete la coadă.",
    "src": "../../../../assets/explorations/logo/mark-tray-queue-s34792.webp"
  },
  {
    "id": "AI19",
    "name": "Tava-U și coada",
    "concept": "Schiță AI pentru A: tava văzută din lateral, cu trei capete la coadă.",
    "src": "../../../../assets/explorations/logo/mark-tray-queue-s34793.webp"
  },
  {
    "id": "AI20",
    "name": "Monograma UB",
    "concept": "Schiță AI pentru N4: U și B pe o singură bară.",
    "src": "../../../../assets/explorations/logo/mark-ub-monogram-s3173.webp"
  },
  {
    "id": "AI21",
    "name": "Monograma UB",
    "concept": "Schiță AI pentru N4: U și B pe o singură bară.",
    "src": "../../../../assets/explorations/logo/mark-ub-monogram-s3174.webp"
  },
  {
    "id": "AI22",
    "name": "Monograma UB",
    "concept": "Schiță AI pentru N4: U și B pe o singură bară.",
    "src": "../../../../assets/explorations/logo/mark-ub-monogram-s3175.webp"
  }
];
